name: inundation_toolbox
dependencies:
  - python=3.10
  - contextily
  - GDAL==3.4.3
  - matplotlib
  - matplotlib_scalebar
  - netCDF4
  - numpy
  - pandas
  - pydantic
  - rasterio==1.2.10
  - scipy
  - pip
  - pip:
    - ugrid
  